#!/bin/sh
preface (){
	N="$1"; shift
	E="$1"; shift
	F=$((10**$E))

	M=$(($N+$F))
	O="${M:1}"

	echo "$O"
}

exposeui (){
	N="$1"; shift
	M="$1"; shift

	while true; do
		socat TCP-LISTEN:59$(preface $M 2),reuseaddr,fork TCP-CONNECT:127.0.0.1:59$(preface $N 2)
		sleep 60
	done
}
launchui (){
	N="$1"; shift
	SIZE="$1"; shift

	while true; do
		/opt/victronenergy/gui/gui -nomouse -display VNC:refreshrate=60:depth=32:size=$SIZE:$N
		sleep 60
	done
}

ui ()(
	N="$1"; shift
	SIZE="$1"; shift

	launchui "$N" "$SIZE"       &
	exposeui "$N" "$(($N + 10))" &

	wait
)

echo 'Waiting for initial UI...'
sleep 60

exposeui 0 10 &
ui 1 840x476  &
ui 2 840x476  &
ui 3 1280x800 &

wait
