#!/bin/sh

exposeui (){
	N="$1"; shift
	M="$1"; shift

	while true; do
		socat TCP-LISTEN:590$M,reuseaddr,fork TCP-CONNECT:127.0.0.1:590$N
	done
}
launchui (){
	N="$1"; shift
	SIZE="$1"; shift

	while true; do
		/opt/victronenergy/gui/gui -nomouse -display VNC:refreshrate=60:depth=32:size=$SIZE:$N
	done
}

ui ()(
	N="$1"; shift
	SIZE="$1"; shift

	launchui "$N" "$SIZE"       &
	exposeui "$N" "$(($N + 1))" &

	wait
)

echo 'Waiting for initial UI...'
sleep 60

exposeui 0 1  &
ui 2 840x476  &
ui 4 840x476  &
ui 6 1270x720 &

wait
