#!/bin/bash
cd "$(dirname "$0")" || exit 1
source "/data/SetupHelper/CommonResources"
if [ $scriptAction == 'NONE' ] ; then
	echo 'Integrates GS into Victron'
	standardActionPrompt
fi
if [ $scriptAction == 'INSTALL' ] ; then
	mkdir /opt/gs
	cp *.py /opt/gs/

	installService $packageName
fi
if [ $scriptAction == 'UNINSTALL' ] ; then
	removeService $packageName
fi

endScript
